org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
loom.platform=forge

minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
forge_version=47.4.10
forge_version_range=[47.4.10,)
loader_version_range=[47,)
minecraft_version_range=[1.20.1,1.21)
forgified_fabric_api_version=0.92.2+1.11.8+1.20.1

mod_version=1.20-10-forge
maven_group=moriyashiine
archives_base_name=bewitchment

cardinal_components_version=5.2.2
fabric_permissions_api_version=0.1-SNAPSHOT
impersonate_version=2.10.3
midnightlib_version=1.4.1-fabric
playerabilitylib_version=1.8.0
reach_entity_attributes_version=2.4.0
step_height_entity_attribute_version=25dabcdad7
terraform_api_version=7.0.3
patchouli_version=1.20.1-84-FABRIC
pehkui_version=3.7.8
trinkets_version=3.7.2
apoli_version=2.9.0
appleskin_version=mc1.20.1-2.5.1
emi_version=1.1.20+1.20.1
